services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stream-notify-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
